DATA:
  BATCH_SIZE: 32
  DATASET: cifar100
  DATA_PATH: /data/dataset/cifar100/extract
  IMG_SIZE: 224
  INTERPOLATION: bicubic
  ZIP_MODE: False
  CACHE_MODE: "part"
  PIN_MEMORY: True
  NUM_WORKERS: 4
  NUM_CLASSES: 100

MODEL:
  PRETRAINED: True
  RESUME: ""
  LABEL_SMOOTHING: 0.1

TRAIN:
  START_EPOCH: 0
  EPOCHS: 50
  WARMUP_EPOCHS: 1
  WEIGHT_DECAY:  1e-4
  BASE_LR: 0.001
  WARMUP_LR: 5e-7
  CLIP_GRAD: 5.0
  AUTO_RESUME: False
  ACCUMULATION_STEPS: 0

  LR_SCHEDULER:
    NAME: cosine

  OPTIMIZER:
    NAME: adamw
    MOMENTUM: 0.9

AUG:
  COLOR_JITTER: 0.4
  AUTO_AUGMENT: rand-m9-mstd0.5-inc1
  REPROB: 0.25
  MIXUP: 0.0
  CUTMIX: 0.0
  CUTMIX_MINMAX: None

TEST:
  CROP: True
  SEQUENTIAL: False

TAG: default
SAVE_FREQ: 1
PRINT_FREQ: 50
SEED: 42
EVAL_MODE: True
THROUGHPUT_MODE: False
