wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.12
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700464296.203827
    t:
      1:
      - 55
      3:
      - 13
      - 23
      4: 3.8.10
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
