name: Test branch or PR
on:
  pull_request:
    types: [opened, review_requested, ready_for_review, synchronize, unlocked]
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - 'dev_test_workflow'
  workflow_dispatch:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

env:
  CO_MODELS_SRC: CoModels

jobs:
  test_job:
    name: Collect information about PR and source
    #runs-on: ${{ matrix.runs-on }} # todo
    runs-on: ubuntu-latest
    steps:
      - name: Set up branch name
        id: event-info
        if: github.event_name == 'push'
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
      - name: Set up model name from workflow_dispatch branch
        if: github.event_name == 'workflow_dispatch'
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
      - name: Checkout CoModels branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.event-info.outputs.branch }}
          path: ${{ env.CO_MODELS_SRC}}

          #- name: Prepare directories
          #  run: |
          #    rel_path="target_dir/${{ steps.pr.outputs.branch }}"
          #    mkdir -p $rel_path
          #    cp -rL $rel_path standalone-dir/

          #- name: Run script
          #  run: |
          #    cd standalone-dir/
          #    bash run.sh

